name = "auto-reaction-bot"
main = "src/index.js"
compatibility_date = "2025-04-13"

[vars]
BOT_TOKEN = "8104653263:AAGBJug5XeN09C4h-bkjTjdSDwzHNJHB9vc"
BOT_USERNAME = "paid_reactBot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "10"
RESTRICTED_CHATS = "1234,5678"
